### ISSUE TITLE
Hi .. How to remove First Index Search bar 

### ISSUE THREAD

**Issue by vivek1608** [YuigaWada/PolioPager#1]

**Comment by YuigaWada** [comment]
If you don't need a search tab, add the following code **_before `super.viewDidLoad().`_**
`         self.needSearchTab = false`

For Example.
```
class ViewController: PolioPagerViewController {
    
    override func viewDidLoad() {
        self.needSearchTab = false
        super.viewDidLoad()
    }
    ...
```

Check [Example/ViewController.swift](https://github.com/YuigaWada/PolioPager/blob/master/Example/Example/ViewController.swift) :)
